-- Standard Chart of Accounts
INSERT INTO chart_of_accounts (code, name, type, parent_id, description) VALUES
('1000', 'Assets', 'asset', NULL, 'Total Assets'),
('1100', 'Current Assets', 'asset', 1, 'Current Assets'),
('1101', 'Cash', 'asset', 2, 'Cash on hand and in banks'),
('1102', 'Accounts Receivable', 'asset', 2, 'Customer receivables'),
('1103', 'Inventory', 'asset', 2, 'Product inventory'),
('1200', 'Fixed Assets', 'asset', 1, 'Fixed Assets'),
('2000', 'Liabilities', 'liability', NULL, 'Total Liabilities'),
('2100', 'Current Liabilities', 'liability', 7, 'Current Liabilities'),
('2101', 'Accounts Payable', 'liability', 8, 'Supplier payables'),
('2102', 'Tax Payable', 'liability', 8, 'Sales tax / VAT payable'),
('2200', 'Long-term Liabilities', 'liability', 7, 'Long-term Liabilities'),
('3000', 'Equity', 'equity', NULL, 'Shareholder Equity'),
('3001', 'Retained Earnings', 'equity', 11, 'Retained earnings'),
('4000', 'Revenue', 'revenue', NULL, 'Operating Revenue'),
('4100', 'Sales Revenue', 'revenue', 13, 'Product sales revenue'),
('4101', 'Booking Revenue', 'revenue', 13, 'Court booking revenue'),
('4102', 'Membership Revenue', 'revenue', 13, 'Membership fees'),
('4103', 'Academy Revenue', 'revenue', 13, 'Academy program revenue'),
('5000', 'Cost of Goods Sold', 'expense', NULL, 'COGS'),
('6000', 'Operating Expenses', 'expense', NULL, 'Operating Expenses'),
('6100', 'Salaries', 'expense', 20, 'Employee salaries'),
('6200', 'Rent', 'expense', 20, 'Rent expense'),
('6300', 'Utilities', 'expense', 20, 'Utility expenses');
