import type { NavDefinition } from './types';
import { T, LIT, COMPOSITE } from './labels';

export const ADMIN_NAV: NavDefinition[] = [
  { id: 'sidebar.dashboard', label: T('admin.sidebar.dashboard'), icon: '📊', path: '/admin', permissionKey: 'sidebar.dashboard' },
  { id: 'sidebar.reports', label: T('admin.sidebar.reports'), icon: '📈', path: '/admin/reports', permissionKey: 'sidebar.reports' },
  {
    id: 'sidebar.organisations',
    label: T('admin.sidebar.organisations'),
    icon: '🏢',
    path: '/admin/organisations',
    permissionKey: 'sidebar.organisations',
    children: [
      { id: 'sidebar.organisations', label: LIT('All Organisations'), path: '/admin/organisations', permissionKey: 'sidebar.organisations' },
      { id: 'sidebar.branch-access', label: LIT('Branch Access'), path: '/admin/branch-access', permissionKey: 'sidebar.branch-access' },
      { id: 'sidebar.admin-bookings', label: LIT('All Bookings'), path: '/admin/bookings', permissionKey: 'sidebar.admin-bookings' },
      { id: 'sidebar.subscription', label: LIT('Subscription Plans'), path: '/admin/subscription', permissionKey: 'sidebar.subscription' },
      { id: 'sidebar.subscription-requests', label: LIT('Subscription Requests'), path: '/admin/subscription/requests', permissionKey: 'sidebar.subscription-requests' },
      { id: 'sidebar.organisation-types', label: T('admin.sidebar.organisation_types'), path: '/admin/organisation-types', permissionKey: 'sidebar.organisation-types' },
      { id: 'sidebar.settlements', label: T('admin.sidebar.settlements'), path: '/admin/settlements', permissionKey: 'sidebar.settlements' },
    ],
  },
  {
    id: 'sidebar.roles',
    label: COMPOSITE([
      { kind: 't', key: 'admin.sidebar.roles' },
      { kind: 'lit', text: ' & ' },
      { kind: 't', key: 'admin.sidebar.permissions' },
    ]),
    icon: '🔐',
    path: '/admin/roles',
    permissionKey: 'sidebar.roles',
    children: [
      { id: 'sidebar.roles', label: T('admin.sidebar.roles'), path: '/admin/roles', permissionKey: 'sidebar.roles' },
      { id: 'sidebar.permissions', label: T('admin.sidebar.permissions'), path: '/admin/permissions', permissionKey: 'sidebar.permissions' },
    ],
  },
  {
    id: 'sidebar.marketplace',
    label: T('admin.sidebar.marketplace'),
    icon: '🛒',
    path: '/admin/product-categories',
    permissionKey: 'sidebar.marketplace',
    requiredFlag: 'app.marketplace_enabled',
    children: [
      { id: 'sidebar.marketplace-products', label: T('admin.sidebar.products'), path: '/admin/marketplace/products', permissionKey: 'sidebar.marketplace-products' },
      { id: 'sidebar.marketplace-orders', label: T('admin.sidebar.orders'), path: '/admin/marketplace/orders', permissionKey: 'sidebar.marketplace-orders' },
      { id: 'sidebar.marketplace-sellers', label: T('admin.sidebar.sellers'), path: '/admin/marketplace/sellers', permissionKey: 'sidebar.marketplace-sellers' },
      { id: 'sidebar.product-categories', label: LIT('Product Categories'), path: '/admin/product-categories', permissionKey: 'sidebar.product-categories' },
      { id: 'sidebar.marketplace-approvals', label: T('admin.sidebar.registrations'), path: '/admin/approvals', permissionKey: 'sidebar.marketplace-approvals' },
      { id: 'sidebar.marketplace-reviews', label: T('admin.sidebar.reviews'), path: '/admin/marketplace/reviews', permissionKey: 'sidebar.marketplace-reviews' },
      { id: 'sidebar.brands', label: T('admin.sidebar.brands'), path: '/admin/brands', permissionKey: 'sidebar.brands' },
      { id: 'sidebar.tags', label: T('admin.sidebar.tags'), path: '/admin/tags', permissionKey: 'sidebar.tags' },
    ],
  },
  {
    id: 'sidebar.bi',
    label: LIT('BI'),
    icon: '📊',
    path: '/admin/bi/dashboard',
    permissionKey: 'sidebar.bi',
    children: [
      { id: 'sidebar.bi-dashboard', label: LIT('Dashboard'), path: '/admin/bi/dashboard', permissionKey: 'sidebar.bi-dashboard' },
      { id: 'sidebar.bi-observability', label: LIT('Observability'), path: '/admin/bi/observability', permissionKey: 'sidebar.bi-observability' },
    ],
  },
  { id: 'sidebar.sports-engine', label: LIT('Sports Engine'), icon: '🧠', path: '/admin/sports-engine', permissionKey: 'sidebar.sports-engine' },
  { id: 'sidebar.reception', label: T('admin.sidebar.reception'), icon: '🏪', path: '/admin/reception', permissionKey: 'sidebar.reception' },
  {
    id: 'sidebar.league',
    label: T('admin.sidebar.league'),
    icon: '🏅',
    path: '/admin/league/dashboard',
    permissionKey: 'sidebar.league',
    children: [
      { id: 'sidebar.league-dashboard', label: T('admin.sidebar.league_dashboard'), path: '/admin/league/dashboard', permissionKey: 'sidebar.league-dashboard' },
      { id: 'sidebar.league-seasons', label: T('admin.sidebar.league_seasons'), path: '/admin/league/seasons', permissionKey: 'sidebar.league-seasons' },
      { id: 'sidebar.league-list', label: T('admin.sidebar.league_list'), path: '/admin/league/list', permissionKey: 'sidebar.league-list' },
      { id: 'sidebar.league-divisions', label: T('admin.sidebar.league_divisions'), path: '/admin/league/divisions', permissionKey: 'sidebar.league-divisions' },
    ],
  },
  {
    id: 'sidebar.tournament',
    label: T('admin.sidebar.tournament'),
    icon: '🏆',
    path: '/admin/tournament/dashboard',
    permissionKey: 'sidebar.tournament',
    children: [
      { id: 'sidebar.tournament-dashboard', label: T('admin.sidebar.tournament_dashboard'), path: '/admin/tournament/dashboard', permissionKey: 'sidebar.tournament-dashboard' },
      { id: 'sidebar.tournament-list', label: T('admin.sidebar.tournament_list'), path: '/admin/tournament/list', permissionKey: 'sidebar.tournament-list' },
      { id: 'sidebar.tournament-matches', label: T('admin.sidebar.tournament_matches'), path: '/admin/tournament/matches', permissionKey: 'sidebar.tournament-matches' },
    ],
  },
  {
    id: 'sidebar.academy',
    label: T('admin.sidebar.academy'),
    icon: '🎓',
    path: '/admin/academy/dashboard',
    permissionKey: 'sidebar.academy',
    children: [
      { id: 'sidebar.academy-dashboard', label: T('admin.sidebar.academy_dashboard'), path: '/admin/academy/dashboard', permissionKey: 'sidebar.academy-dashboard' },
      { id: 'sidebar.academy-programs', label: T('admin.sidebar.academy_programs'), path: '/admin/academy/programs', permissionKey: 'sidebar.academy-programs' },
      { id: 'sidebar.academy-groups', label: T('admin.sidebar.academy_groups'), path: '/admin/academy/groups', permissionKey: 'sidebar.academy-groups' },
      { id: 'sidebar.academy-enrollments', label: T('admin.sidebar.academy_enrollments'), path: '/admin/academy/enrollments', permissionKey: 'sidebar.academy-enrollments' },
      { id: 'sidebar.academy-attendance', label: T('admin.sidebar.academy_attendance'), path: '/admin/academy/attendance', permissionKey: 'sidebar.academy-attendance' },
    ],
  },
  { id: 'sidebar.coaches-admin', label: T('admin.sidebar.coaches'), icon: '👨‍🏫', path: '/admin/coaches', permissionKey: 'sidebar.coaches-admin' },
  {
    id: 'sidebar.membership',
    label: T('admin.sidebar.membership'),
    icon: '⭐',
    path: '/admin/membership/plans',
    permissionKey: 'sidebar.membership',
    children: [
      { id: 'membership.plans', label: T('admin.sidebar.plans'), path: '/admin/membership/plans', permissionKey: 'membership.plans' },
      { id: 'membership.campaigns', label: T('admin.sidebar.campaigns'), path: '/admin/membership/campaigns', permissionKey: 'membership.campaigns' },
      { id: 'membership.rewards', label: T('admin.sidebar.rewards'), path: '/admin/membership/rewards', permissionKey: 'membership.rewards' },
    ],
  },
  {
    id: 'sidebar.pricing',
    label: T('admin.sidebar.pricing'),
    icon: '💰',
    path: '/admin/pricing/rules',
    permissionKey: 'sidebar.pricing',
    children: [
      { id: 'pricing.rules', label: T('admin.sidebar.rules'), path: '/admin/pricing/rules', permissionKey: 'pricing.rules' },
      { id: 'pricing.preview', label: LIT('Price Preview'), path: '/admin/pricing/preview', permissionKey: 'pricing.preview' },
    ],
  },
  {
    id: 'sidebar.crm',
    label: LIT('CRM'),
    icon: '🤝',
    path: '/admin/crm/dashboard',
    permissionKey: 'sidebar.crm',
    children: [
      { id: 'sidebar.crm-dashboard', label: LIT('Dashboard'), path: '/admin/crm/dashboard', permissionKey: 'sidebar.crm-dashboard' },
      { id: 'sidebar.crm-customers', label: LIT('Customers'), path: '/admin/crm/customers', permissionKey: 'sidebar.crm-customers' },
      { id: 'sidebar.crm-segments', label: LIT('Segments'), path: '/admin/crm/segments', permissionKey: 'sidebar.crm-segments' },
      { id: 'sidebar.crm-leads', label: LIT('Leads'), path: '/admin/crm/leads', permissionKey: 'sidebar.crm-leads' },
      { id: 'sidebar.crm-campaigns', label: LIT('Campaigns'), path: '/admin/crm/campaigns', permissionKey: 'sidebar.crm-campaigns' },
      { id: 'sidebar.crm-communications', label: LIT('Communications'), path: '/admin/crm/communications', permissionKey: 'sidebar.crm-communications' },
    ],
  },
  {
    id: 'sidebar.hr',
    label: LIT('HR'),
    icon: '👥',
    path: '/admin/hr/dashboard',
    permissionKey: 'sidebar.hr',
    children: [
      { id: 'sidebar.hr-dashboard', label: LIT('Dashboard'), path: '/admin/hr/dashboard', permissionKey: 'sidebar.hr-dashboard' },
      { id: 'sidebar.hr-employees', label: LIT('Employees'), path: '/admin/hr/employees', permissionKey: 'sidebar.hr-employees' },
      { id: 'sidebar.hr-departments', label: LIT('Departments'), path: '/admin/hr/departments', permissionKey: 'sidebar.hr-departments' },
      { id: 'sidebar.hr-leave', label: LIT('Leave'), path: '/admin/hr/leave', permissionKey: 'sidebar.hr-leave' },
      { id: 'sidebar.hr-attendance', label: LIT('Attendance'), path: '/admin/hr/attendance', permissionKey: 'sidebar.hr-attendance' },
      { id: 'sidebar.hr-payroll', label: LIT('Payroll'), path: '/admin/hr/payroll', permissionKey: 'sidebar.hr-payroll' },
    ],
  },
  { id: 'sidebar.community-admin', label: LIT('Community Events'), icon: '🎉', path: '/admin/community-events', permissionKey: 'sidebar.community-admin' },
  {
    id: 'sidebar.notifications',
    label: T('admin.sidebar.notifications'),
    icon: '🔔',
    path: '/admin/notifications/broadcast',
    permissionKey: 'sidebar.notifications',
    children: [
      { id: 'notifications.broadcast', label: T('admin.sidebar.broadcast'), path: '/admin/notifications/broadcast', permissionKey: 'notifications.broadcast' },
      { id: 'notifications.analytics', label: T('admin.sidebar.analytics'), path: '/admin/notifications/analytics', permissionKey: 'notifications.analytics' },
      { id: 'notifications.dead-letters', label: LIT('Dead Letters'), path: '/admin/notifications/dead-letters', permissionKey: 'notifications.dead-letters' },
      { id: 'notification_templates.view', label: T('admin.sidebar.templates'), path: '/admin/templates', permissionKey: 'notification_templates.view' },
      { id: 'notification_types.view', label: LIT('Types'), path: '/admin/notification-types', permissionKey: 'notification_types.view' },
      { id: 'notifications.config.manage', label: LIT('⚙️ Config'), path: '/admin/notifications/config', permissionKey: 'notifications.config.manage' },
    ],
  },
  { id: 'sidebar.ads', label: T('admin.sidebar.ads'), icon: '📢', path: '/admin/ads', permissionKey: 'sidebar.ads', requiredFlag: 'community.events_enabled' },
  {
    id: 'sidebar.admin-settings',
    label: LIT('Admin Settings'),
    icon: '⚙️',
    path: '/admin/sports',
    permissionKey: 'sidebar.admin-settings',
    children: [
      { id: 'sidebar.sports', label: T('admin.sidebar.sports'), path: '/admin/sports', permissionKey: 'sidebar.sports' },
      {
        id: 'sidebar.finance',
        label: T('admin.sidebar.finance'),
        path: '/admin/finance',
        permissionKey: 'sidebar.finance',
        children: [
          { id: 'sidebar.finance-dashboard', label: LIT('Finance Dashboard'), path: '/admin/finance', permissionKey: 'sidebar.finance-dashboard' },
          { id: 'sidebar.finance-ledger', label: T('admin.sidebar.ledger'), path: '/admin/finance/ledger', permissionKey: 'sidebar.finance-ledger' },
          { id: 'sidebar.finance-reports', label: LIT('Reports'), path: '/admin/finance/reports', permissionKey: 'sidebar.finance-reports' },
          { id: 'sidebar.withdrawal-requests', label: LIT('Withdrawal Requests'), path: '/admin/withdrawal-requests', permissionKey: 'sidebar.withdrawal-requests' },
          { id: 'sidebar.withdrawals-queue', label: LIT('Withdrawals Queue'), path: '/admin/withdrawals', permissionKey: 'sidebar.withdrawals-queue' },
          { id: 'sidebar.coupons', label: T('admin.sidebar.coupons'), path: '/admin/coupons', permissionKey: 'sidebar.coupons' },
          { id: 'sidebar.finance-transactions', label: LIT('Finance (Legacy)'), path: '/admin/financial-ops', permissionKey: 'sidebar.finance-transactions' },
          { id: 'sidebar.banks', label: T('admin.sidebar.banks'), path: '/admin/banks', permissionKey: 'sidebar.banks' },
          { id: 'sidebar.bank-branches', label: LIT('Bank Branches'), path: '/admin/bank-branches', permissionKey: 'sidebar.bank-branches' },
        ],
      },
      {
        id: 'sidebar.payment-methods',
        label: LIT('Payments Config'),
        path: '/admin/payment-methods',
        permissionKey: 'sidebar.payment-methods',
        children: [
          { id: 'sidebar.payment-methods', label: LIT('Payment Methods'), path: '/admin/payment-methods', permissionKey: 'sidebar.payment-methods' },
          { id: 'sidebar.payment-gateways', label: LIT('Gateway Config'), path: '/admin/payment-gateways', permissionKey: 'sidebar.payment-gateways' },
        ],
      },
      {
        id: 'sidebar.countries',
        label: T('admin.sidebar.localization'),
        icon: '🌍',
        path: '/admin/countries',
        permissionKey: 'sidebar.countries',
        children: [
          { id: 'sidebar.countries', label: T('admin.sidebar.countries'), path: '/admin/countries', permissionKey: 'sidebar.countries' },
          { id: 'sidebar.currencies', label: T('admin.sidebar.currencies'), path: '/admin/currencies', permissionKey: 'sidebar.currencies' },
          { id: 'sidebar.languages', label: T('admin.sidebar.languages'), path: '/admin/languages', permissionKey: 'sidebar.languages' },
          { id: 'sidebar.translations', label: T('admin.sidebar.translations'), path: '/admin/translations', permissionKey: 'sidebar.translations' },
        ],
      },
      { id: 'sidebar.amenities', label: T('admin.sidebar.amenities'), path: '/admin/amenities', permissionKey: 'sidebar.amenities' },
      {
        id: 'sidebar.app-settings-menu',
        label: LIT('App Settings'),
        path: '/admin/sidebar-layout',
        permissionKey: 'sidebar.app-settings-menu',
        children: [
          { id: 'sidebar.layout.manage', label: LIT('Set Sidebar Layout'), path: '/admin/sidebar-layout', permissionKey: 'sidebar.layout.manage' },
          { id: 'sidebar.app-settings', label: T('admin.sidebar.branding'), path: '/admin/app-settings', permissionKey: 'sidebar.app-settings' },
          { id: 'sidebar.design-tokens', label: LIT('Appearance Studio'), path: '/admin/design-tokens', permissionKey: 'sidebar.design-tokens' },
          { id: 'sidebar.cms', label: LIT('CMS'), path: '/admin/cms', permissionKey: 'sidebar.cms' },
        ],
      },
    ],
  },
  { id: 'sidebar.users', label: T('admin.sidebar.users'), icon: '👥', path: '/admin/users', permissionKey: 'sidebar.users' },
  {
    id: 'sidebar.inventory',
    label: LIT('Inventory'),
    icon: '📦',
    path: '/admin/inventory/stock',
    permissionKey: 'sidebar.inventory',
    children: [
      { id: 'sidebar.inventory-stock', label: LIT('Stock Levels'), path: '/admin/inventory/stock', permissionKey: 'sidebar.inventory-stock' },
      { id: 'sidebar.inventory-warehouses', label: LIT('Warehouses'), path: '/admin/inventory/warehouses', permissionKey: 'sidebar.inventory-warehouses' },
      { id: 'sidebar.inventory-suppliers', label: LIT('Suppliers'), path: '/admin/inventory/suppliers', permissionKey: 'sidebar.inventory-suppliers' },
      { id: 'sidebar.inventory-purchase-orders', label: LIT('Purchase Orders'), path: '/admin/inventory/purchase-orders', permissionKey: 'sidebar.inventory-purchase-orders' },
    ],
  },
  { id: 'sidebar.mobile', label: LIT('Mobile'), icon: '📱', path: '/admin/mobile/dashboard', permissionKey: 'sidebar.mobile' },
  { id: 'sidebar.integration', label: LIT('Integration'), icon: '🔌', path: '/admin/integration/api-keys', permissionKey: 'sidebar.integration' },
  { id: 'sidebar.webhooks', label: T('admin.sidebar.webhooks'), icon: '🔗', path: '/admin/webhooks', permissionKey: 'sidebar.webhooks' },
  {
    id: 'sidebar.security-dashboard',
    label: T('admin.sidebar.security'),
    icon: '🛡️',
    path: '/admin/security',
    permissionKey: 'sidebar.security-dashboard',
    children: [
      { id: 'sidebar.security-dashboard', label: LIT('Security Dashboard'), path: '/admin/security', permissionKey: 'sidebar.security-dashboard' },
      { id: 'sidebar.active-sessions', label: LIT('Active Sessions'), path: '/admin/security/sessions', permissionKey: 'sidebar.active-sessions' },
      { id: 'sidebar.failed-logins', label: LIT('Failed Logins'), path: '/admin/security/failed-logins', permissionKey: 'sidebar.failed-logins' },
      { id: 'sidebar.upload-security', label: LIT('Upload Security'), path: '/admin/security/uploads', permissionKey: 'sidebar.upload-security' },
      { id: 'sidebar.system-health', label: LIT('System Health'), path: '/admin/security/system-health', permissionKey: 'sidebar.system-health' },
      { id: 'system_settings.view', label: LIT('System Admin'), path: '/admin/system', permissionKey: 'system_settings.view' },
      { id: 'membership.view', label: LIT('Membership'), path: '/admin/membership', permissionKey: 'membership.view' },
      { id: 'sidebar.audit', label: LIT('Audit Log'), path: '/admin/audit-logs', permissionKey: 'sidebar.audit' },
      { id: 'sidebar.feature-flags', label: LIT('Feature Flags'), path: '/admin/feature-flags', permissionKey: 'sidebar.feature-flags' },
      { id: 'support.tickets.view', label: LIT('Support Tickets'), path: '/admin/support/tickets', permissionKey: 'support.tickets.view' },
      { id: 'queue.view', label: LIT('Queue Management'), path: '/admin/queues', permissionKey: 'queue.view' },
    ],
  },
];
