import type { NavDefinition } from './types';
import { T, LIT, COMPOSITE } from './labels';
import { buildNavIdKeyMaps } from './id-key';

export const ADMIN_NAV: NavDefinition[] = [
  {
    id: 'nav.admin.domain.dashboard',
    label: T('nav.admin.domain.dashboard'),
    icon: '📊',
    path: '/admin',
    children: [
      { id: 'nav.admin.dashboard', label: T('admin.sidebar.dashboard'), icon: '📊', path: '/admin', permissionKey: 'sidebar.dashboard' },
      { id: 'nav.admin.reports', label: T('admin.sidebar.reports'), icon: '📈', path: '/admin/reports', permissionKey: 'sidebar.reports' },
    ],
  },
  {
    id: 'nav.admin.domain.people',
    label: T('nav.admin.domain.people'),
    icon: '👥',
    path: '/admin/organisations',
    children: [
      { id: 'nav.admin.users', label: T('admin.sidebar.users'), icon: '👥', path: '/admin/users', permissionKey: 'sidebar.users' },
      {
        id: 'nav.admin.roles',
        label: COMPOSITE([
          { kind: 't', key: 'admin.sidebar.roles' },
          { kind: 'lit', text: ' & ' },
          { kind: 't', key: 'admin.sidebar.permissions' },
        ]),
        icon: '🔐',
        path: '/admin/roles',
        permissionKey: 'sidebar.roles',
        children: [
          { id: 'nav.admin.roles.landing', label: T('admin.sidebar.roles'), path: '/admin/roles', permissionKey: 'sidebar.roles' },
          { id: 'nav.admin.permissions', label: T('admin.sidebar.permissions'), path: '/admin/permissions', permissionKey: 'sidebar.permissions' },
        ],
      },
      {
        id: 'nav.admin.organisations',
        label: T('admin.sidebar.organisations'),
        icon: '🏢',
        path: '/admin/organisations',
        permissionKey: 'sidebar.organisations',
        children: [
          { id: 'nav.admin.organisations.landing', label: LIT('All Organisations'), path: '/admin/organisations', permissionKey: 'sidebar.organisations' },
          { id: 'nav.admin.branch-access', label: LIT('Branch Access'), path: '/admin/branch-access', permissionKey: 'sidebar.branch-access' },
          { id: 'nav.admin.organisation-types', label: T('admin.sidebar.organisation_types'), path: '/admin/organisation-types', permissionKey: 'sidebar.organisation-types' },
        ],
      },
      {
        id: 'nav.admin.membership',
        label: T('admin.sidebar.membership'),
        icon: '⭐',
        path: '/admin/membership/plans',
        permissionKey: 'sidebar.membership',
        children: [
          { id: 'nav.admin.membership-plans', label: T('admin.sidebar.plans'), path: '/admin/membership/plans', permissionKey: 'membership.plans' },
          { id: 'nav.admin.membership-campaigns', label: T('admin.sidebar.campaigns'), path: '/admin/membership/campaigns', permissionKey: 'membership.campaigns' },
          { id: 'nav.admin.membership-rewards', label: T('admin.sidebar.rewards'), path: '/admin/membership/rewards', permissionKey: 'membership.rewards' },
        ],
      },
      {
        id: 'nav.admin.crm',
        label: LIT('CRM'),
        icon: '🤝',
        path: '/admin/crm/dashboard',
        permissionKey: 'sidebar.crm',
        children: [
          { id: 'nav.admin.crm-dashboard', label: LIT('Dashboard'), path: '/admin/crm/dashboard', permissionKey: 'sidebar.crm-dashboard' },
          { id: 'nav.admin.crm-customers', label: LIT('Customers'), path: '/admin/crm/customers', permissionKey: 'sidebar.crm-customers' },
          { id: 'nav.admin.crm-segments', label: LIT('Segments'), path: '/admin/crm/segments', permissionKey: 'sidebar.crm-segments' },
          { id: 'nav.admin.crm-leads', label: LIT('Leads'), path: '/admin/crm/leads', permissionKey: 'sidebar.crm-leads' },
          { id: 'nav.admin.crm-campaigns', label: LIT('Campaigns'), path: '/admin/crm/campaigns', permissionKey: 'sidebar.crm-campaigns' },
          { id: 'nav.admin.crm-communications', label: LIT('Communications'), path: '/admin/crm/communications', permissionKey: 'sidebar.crm-communications' },
        ],
      },
      {
        id: 'nav.admin.hr',
        label: LIT('HR'),
        icon: '👥',
        path: '/admin/hr/dashboard',
        permissionKey: 'sidebar.hr',
        children: [
          { id: 'nav.admin.hr-dashboard', label: LIT('Dashboard'), path: '/admin/hr/dashboard', permissionKey: 'sidebar.hr-dashboard' },
          { id: 'nav.admin.hr-employees', label: LIT('Employees'), path: '/admin/hr/employees', permissionKey: 'sidebar.hr-employees' },
          { id: 'nav.admin.hr-departments', label: LIT('Departments'), path: '/admin/hr/departments', permissionKey: 'sidebar.hr-departments' },
          { id: 'nav.admin.hr-leave', label: LIT('Leave'), path: '/admin/hr/leave', permissionKey: 'sidebar.hr-leave' },
          { id: 'nav.admin.hr-attendance', label: LIT('Attendance'), path: '/admin/hr/attendance', permissionKey: 'sidebar.hr-attendance' },
          { id: 'nav.admin.hr-payroll', label: LIT('Payroll'), path: '/admin/hr/payroll', permissionKey: 'sidebar.hr-payroll' },
        ],
      },
    ],
  },
  {
    id: 'nav.admin.domain.facilities',
    label: T('nav.admin.domain.facilities'),
    icon: '🏟️',
    path: '/admin/reception',
    children: [
      { id: 'nav.admin.reception', label: T('admin.sidebar.reception'), icon: '🏪', path: '/admin/reception', permissionKey: 'sidebar.reception' },
      { id: 'nav.admin.admin-bookings', label: LIT('All Bookings'), path: '/admin/bookings', permissionKey: 'sidebar.admin-bookings' },
      { id: 'nav.admin.sports-engine', label: LIT('Sports Engine'), icon: '🧠', path: '/admin/sports-engine', permissionKey: 'sidebar.sports-engine' },
      { id: 'nav.admin.sports', label: T('admin.sidebar.sports'), path: '/admin/sports', permissionKey: 'sidebar.sports' },
      { id: 'nav.admin.amenities', label: T('admin.sidebar.amenities'), path: '/admin/amenities', permissionKey: 'sidebar.amenities' },
      { id: 'nav.admin.community', label: LIT('Community Events'), icon: '🎉', path: '/admin/community-events', permissionKey: 'sidebar.community-admin' },
      {
        id: 'nav.admin.inventory',
        label: LIT('Inventory'),
        icon: '📦',
        path: '/admin/inventory/stock',
        permissionKey: 'sidebar.inventory',
        children: [
          { id: 'nav.admin.inventory-stock', label: LIT('Stock Levels'), path: '/admin/inventory/stock', permissionKey: 'sidebar.inventory-stock' },
          { id: 'nav.admin.inventory-warehouses', label: LIT('Warehouses'), path: '/admin/inventory/warehouses', permissionKey: 'sidebar.inventory-warehouses' },
          { id: 'nav.admin.inventory-suppliers', label: LIT('Suppliers'), path: '/admin/inventory/suppliers', permissionKey: 'sidebar.inventory-suppliers' },
          { id: 'nav.admin.inventory-purchase-orders', label: LIT('Purchase Orders'), path: '/admin/inventory/purchase-orders', permissionKey: 'sidebar.inventory-purchase-orders' },
        ],
      },
    ],
  },
  {
    id: 'nav.admin.domain.coaching',
    label: T('nav.admin.domain.coaching'),
    icon: '🎓',
    path: '/admin/academy/dashboard',
    children: [
      {
        id: 'nav.admin.academy',
        label: T('admin.sidebar.academy'),
        icon: '🎓',
        path: '/admin/academy/dashboard',
        permissionKey: 'sidebar.academy',
        children: [
          { id: 'nav.admin.academy-dashboard', label: T('admin.sidebar.academy_dashboard'), path: '/admin/academy/dashboard', permissionKey: 'sidebar.academy-dashboard' },
          { id: 'nav.admin.academy-programs', label: T('admin.sidebar.academy_programs'), path: '/admin/academy/programs', permissionKey: 'sidebar.academy-programs' },
          { id: 'nav.admin.academy-groups', label: T('admin.sidebar.academy_groups'), path: '/admin/academy/groups', permissionKey: 'sidebar.academy-groups' },
          { id: 'nav.admin.academy-enrollments', label: T('admin.sidebar.academy_enrollments'), path: '/admin/academy/enrollments', permissionKey: 'sidebar.academy-enrollments' },
          { id: 'nav.admin.academy-attendance', label: T('admin.sidebar.academy_attendance'), path: '/admin/academy/attendance', permissionKey: 'sidebar.academy-attendance' },
        ],
      },
      { id: 'nav.admin.coaches', label: T('admin.sidebar.coaches'), icon: '👨‍🏫', path: '/admin/coaches', permissionKey: 'sidebar.coaches-admin' },
    ],
  },
  {
    id: 'nav.admin.domain.competitions',
    label: T('nav.admin.domain.competitions'),
    icon: '🏆',
    path: '/admin/league/dashboard',
    children: [
      {
        id: 'nav.admin.league',
        label: T('admin.sidebar.league'),
        icon: '🏅',
        path: '/admin/league/dashboard',
        permissionKey: 'sidebar.league',
        children: [
          { id: 'nav.admin.league-dashboard', label: T('admin.sidebar.league_dashboard'), path: '/admin/league/dashboard', permissionKey: 'sidebar.league-dashboard' },
          { id: 'nav.admin.league-seasons', label: T('admin.sidebar.league_seasons'), path: '/admin/league/seasons', permissionKey: 'sidebar.league-seasons' },
          { id: 'nav.admin.league-list', label: T('admin.sidebar.league_list'), path: '/admin/league/list', permissionKey: 'sidebar.league-list' },
          { id: 'nav.admin.league-divisions', label: T('admin.sidebar.league_divisions'), path: '/admin/league/divisions', permissionKey: 'sidebar.league-divisions' },
        ],
      },
      {
        id: 'nav.admin.tournament',
        label: T('admin.sidebar.tournament'),
        icon: '🏆',
        path: '/admin/tournament/dashboard',
        permissionKey: 'sidebar.tournament',
        children: [
          { id: 'nav.admin.tournament-dashboard', label: T('admin.sidebar.tournament_dashboard'), path: '/admin/tournament/dashboard', permissionKey: 'sidebar.tournament-dashboard' },
          { id: 'nav.admin.tournament-list', label: T('admin.sidebar.tournament_list'), path: '/admin/tournament/list', permissionKey: 'sidebar.tournament-list' },
          { id: 'nav.admin.tournament-matches', label: T('admin.sidebar.tournament_matches'), path: '/admin/tournament/matches', permissionKey: 'sidebar.tournament-matches' },
        ],
      },
    ],
  },
  {
    id: 'nav.admin.domain.commerce',
    label: T('nav.admin.domain.commerce'),
    icon: '🛒',
    path: '/admin/product-categories',
    children: [
      {
        id: 'nav.admin.marketplace',
        label: T('admin.sidebar.marketplace'),
        icon: '🛒',
        path: '/admin/product-categories',
        permissionKey: 'sidebar.marketplace',
        requiredFlag: 'app.marketplace_enabled',
        children: [
          { id: 'nav.admin.marketplace-products', label: T('admin.sidebar.products'), path: '/admin/marketplace/products', permissionKey: 'sidebar.marketplace-products' },
          { id: 'nav.admin.marketplace-orders', label: T('admin.sidebar.orders'), path: '/admin/marketplace/orders', permissionKey: 'sidebar.marketplace-orders' },
          { id: 'nav.admin.marketplace-sellers', label: T('admin.sidebar.sellers'), path: '/admin/marketplace/sellers', permissionKey: 'sidebar.marketplace-sellers' },
          { id: 'nav.admin.product-categories', label: LIT('Product Categories'), path: '/admin/product-categories', permissionKey: 'sidebar.product-categories' },
          { id: 'nav.admin.marketplace-approvals', label: T('admin.sidebar.registrations'), path: '/admin/approvals', permissionKey: 'sidebar.marketplace-approvals' },
          { id: 'nav.admin.marketplace-reviews', label: T('admin.sidebar.reviews'), path: '/admin/marketplace/reviews', permissionKey: 'sidebar.marketplace-reviews' },
          { id: 'nav.admin.brands', label: T('admin.sidebar.brands'), path: '/admin/brands', permissionKey: 'sidebar.brands' },
          { id: 'nav.admin.tags', label: T('admin.sidebar.tags'), path: '/admin/tags', permissionKey: 'sidebar.tags' },
        ],
      },
      {
        id: 'nav.admin.pricing',
        label: T('admin.sidebar.pricing'),
        icon: '💰',
        path: '/admin/pricing/rules',
        permissionKey: 'sidebar.pricing',
        children: [
          { id: 'nav.admin.pricing-rules', label: T('admin.sidebar.rules'), path: '/admin/pricing/rules', permissionKey: 'pricing.rules' },
          { id: 'nav.admin.pricing-preview', label: LIT('Price Preview'), path: '/admin/pricing/preview', permissionKey: 'pricing.preview' },
        ],
      },
      { id: 'nav.admin.subscription', label: LIT('Subscription Plans'), path: '/admin/subscription', permissionKey: 'sidebar.subscription' },
      { id: 'nav.admin.subscription-requests', label: LIT('Subscription Requests'), path: '/admin/subscription/requests', permissionKey: 'sidebar.subscription-requests' },
      { id: 'nav.admin.settlements', label: T('admin.sidebar.settlements'), path: '/admin/settlements', permissionKey: 'sidebar.settlements' },
      { id: 'nav.admin.settlements-bookings', label: LIT('Booking Settlements'), path: '/admin/settlements/bookings', permissionKey: 'sidebar.settlements-bookings' },
      { id: 'nav.admin.coupons', label: T('admin.sidebar.coupons'), path: '/admin/coupons', permissionKey: 'sidebar.coupons' },
      { id: 'nav.admin.ads', label: T('admin.sidebar.ads'), icon: '📢', path: '/admin/ads', permissionKey: 'sidebar.ads', requiredFlag: 'community.events_enabled' },
    ],
  },
  {
    id: 'nav.admin.domain.finance',
    label: T('nav.admin.domain.finance'),
    icon: '💰',
    path: '/admin/finance',
    children: [
      { id: 'nav.admin.finance-dashboard', label: LIT('Finance Dashboard'), path: '/admin/finance', permissionKey: 'sidebar.finance-dashboard' },
      { id: 'nav.admin.finance-ledger', label: T('admin.sidebar.ledger'), path: '/admin/finance/ledger', permissionKey: 'sidebar.finance-ledger' },
      { id: 'nav.admin.finance-reports', label: LIT('Reports'), path: '/admin/finance/reports', permissionKey: 'sidebar.finance-reports' },
      { id: 'nav.admin.banks', label: T('admin.sidebar.banks'), path: '/admin/banks', permissionKey: 'sidebar.banks' },
      { id: 'nav.admin.bank-branches', label: LIT('Bank Branches'), path: '/admin/bank-branches', permissionKey: 'sidebar.bank-branches' },
      { id: 'nav.admin.finance-transactions', label: LIT('Finance (Legacy)'), path: '/admin/financial-ops', permissionKey: 'sidebar.finance-transactions' },
      { id: 'nav.admin.withdrawal-requests', label: LIT('Withdrawal Requests'), path: '/admin/withdrawal-requests', permissionKey: 'sidebar.withdrawal-requests' },
      { id: 'nav.admin.withdrawals-queue', label: LIT('Withdrawals Queue'), path: '/admin/withdrawals', permissionKey: 'sidebar.withdrawals-queue' },
    ],
  },
  {
    id: 'nav.admin.domain.accounting',
    label: LIT('Accounting'),
    icon: '📒',
    path: '/admin/accounting/dashboard',
    permissionKey: 'sidebar.accounting',
    children: [
      { id: 'nav.admin.accounting-dashboard', label: LIT('Dashboard'), path: '/admin/accounting/dashboard', permissionKey: 'sidebar.accounting-dashboard' },
      { id: 'nav.admin.accounting-coa', label: LIT('Chart of Accounts'), path: '/admin/accounting/accounts', permissionKey: 'sidebar.accounting-coa' },
      { id: 'nav.admin.accounting-journal', label: LIT('Journal'), path: '/admin/accounting/journal', permissionKey: 'sidebar.accounting-journal' },
      { id: 'nav.admin.accounting-gl', label: LIT('General Ledger'), path: '/admin/accounting/ledger', permissionKey: 'sidebar.accounting-gl' },
      { id: 'nav.admin.accounting-periods', label: LIT('Periods'), path: '/admin/accounting/periods', permissionKey: 'sidebar.accounting-periods' },
      { id: 'nav.admin.accounting-invoices', label: LIT('Invoices'), path: '/admin/accounting/invoices', permissionKey: 'sidebar.accounting-invoices' },
      { id: 'nav.admin.accounting-tax', label: LIT('Tax Rates'), path: '/admin/accounting/tax-rates', permissionKey: 'sidebar.accounting-tax' },
      { id: 'nav.admin.accounting-mappings', label: LIT('Event Mappings'), path: '/admin/accounting/mappings', permissionKey: 'sidebar.accounting-mappings' },
      { id: 'nav.admin.accounting-templates', label: LIT('Account Templates'), path: '/admin/accounting/templates', permissionKey: 'sidebar.accounting-templates' },
      { id: 'nav.admin.accounting-tax-report', label: LIT('Tax Summary'), path: '/admin/accounting/tax-report', permissionKey: 'sidebar.accounting-tax-report' },
    ],
  },
  {
    id: 'nav.admin.domain.platform',
    label: T('nav.admin.domain.platform'),
    icon: '⚙️',
    path: '/admin/security',
    children: [
      {
        id: 'nav.admin.security',
        label: T('admin.sidebar.security'),
        icon: '🛡️',
        path: '/admin/security',
        permissionKey: 'sidebar.security-dashboard',
        children: [
          { id: 'nav.admin.security.landing', label: LIT('Security Dashboard'), path: '/admin/security', permissionKey: 'sidebar.security-dashboard' },
          { id: 'nav.admin.security-sessions', label: LIT('Active Sessions'), path: '/admin/security/sessions', permissionKey: 'sidebar.active-sessions' },
          { id: 'nav.admin.security-failed-logins', label: LIT('Failed Logins'), path: '/admin/security/failed-logins', permissionKey: 'sidebar.failed-logins' },
          { id: 'nav.admin.security-uploads', label: LIT('Upload Security'), path: '/admin/security/uploads', permissionKey: 'sidebar.upload-security' },
          { id: 'nav.admin.security-system-health', label: LIT('System Health'), path: '/admin/security/system-health', permissionKey: 'sidebar.system-health' },
          { id: 'nav.admin.system-settings', label: LIT('System Admin'), path: '/admin/system', permissionKey: 'app-settings.view' },
          { id: 'nav.admin.membership-view', label: LIT('Membership'), path: '/admin/membership', permissionKey: 'membership.view' },
          { id: 'nav.admin.audit', label: LIT('Audit Log'), path: '/admin/audit-logs', permissionKey: 'sidebar.audit' },
          { id: 'nav.admin.feature-flags', label: LIT('Feature Flags'), path: '/admin/feature-flags', permissionKey: 'sidebar.feature-flags' },
          { id: 'nav.admin.support-tickets', label: LIT('Support Tickets'), path: '/admin/support/tickets', permissionKey: 'support.tickets.view' },
          { id: 'nav.admin.queue', label: LIT('Queue Management'), path: '/admin/queues', permissionKey: 'sidebar.queue-management' },
        ],
      },
      {
        id: 'nav.admin.notifications',
        label: T('admin.sidebar.notifications'),
        icon: '🔔',
        path: '/admin/notifications/broadcast',
        permissionKey: 'sidebar.notifications',
        children: [
          { id: 'nav.admin.notifications-broadcast', label: T('admin.sidebar.broadcast'), path: '/admin/notifications/broadcast', permissionKey: 'notifications.broadcast' },
          { id: 'nav.admin.notifications-analytics', label: T('admin.sidebar.analytics'), path: '/admin/notifications/analytics', permissionKey: 'notifications.analytics' },
          { id: 'nav.admin.notifications-dead-letters', label: LIT('Dead Letters'), path: '/admin/notifications/dead-letters', permissionKey: 'notifications.dead-letters' },
          { id: 'nav.admin.notification-templates', label: T('admin.sidebar.templates'), path: '/admin/templates', permissionKey: 'notification_templates.view' },
          { id: 'nav.admin.notification-types', label: LIT('Types'), path: '/admin/notification-types', permissionKey: 'notification_types.view' },
          { id: 'nav.admin.notifications-config', label: LIT('⚙️ Config'), path: '/admin/notifications/config', permissionKey: 'notifications.config.manage' },
        ],
      },
      { id: 'nav.admin.integration', label: LIT('Integration'), icon: '🔌', path: '/admin/integration/api-keys', permissionKey: 'sidebar.integration' },
      { id: 'nav.admin.webhooks', label: T('admin.sidebar.webhooks'), icon: '🔗', path: '/admin/webhooks', permissionKey: 'sidebar.webhooks' },
      { id: 'nav.admin.mobile', label: LIT('Mobile'), icon: '📱', path: '/admin/mobile/dashboard', permissionKey: 'sidebar.mobile' },
      {
        id: 'nav.admin.admin-settings',
        label: LIT('Admin Settings'),
        icon: '⚙️',
        path: '/admin/sidebar-layout',
        permissionKey: 'sidebar.admin-settings',
        children: [
          {
            id: 'nav.admin.app-settings',
            label: LIT('App Settings'),
            path: '/admin/sidebar-layout',
            permissionKey: 'sidebar.app-settings-menu',
            children: [
              { id: 'nav.admin.sidebar-layout', label: LIT('Set Sidebar Layout'), path: '/admin/sidebar-layout', permissionKey: 'sidebar.layout.manage' },
              { id: 'nav.admin.branding', label: T('admin.sidebar.branding'), path: '/admin/app-settings', permissionKey: 'sidebar.app-settings' },
              { id: 'nav.admin.design-tokens', label: LIT('Appearance Studio'), path: '/admin/design-tokens', permissionKey: 'sidebar.design-tokens' },
              { id: 'nav.admin.cms', label: LIT('CMS'), path: '/admin/cms', permissionKey: 'sidebar.cms' },
            ],
          },
          {
            id: 'nav.admin.countries',
            label: T('admin.sidebar.localization'),
            icon: '🌍',
            path: '/admin/countries',
            permissionKey: 'sidebar.countries',
            children: [
              { id: 'nav.admin.countries.landing', label: T('admin.sidebar.countries'), path: '/admin/countries', permissionKey: 'sidebar.countries' },
              { id: 'nav.admin.currencies', label: T('admin.sidebar.currencies'), path: '/admin/currencies', permissionKey: 'sidebar.currencies' },
              { id: 'nav.admin.languages', label: T('admin.sidebar.languages'), path: '/admin/languages', permissionKey: 'sidebar.languages' },
              { id: 'nav.admin.translations', label: T('admin.sidebar.translations'), path: '/admin/translations', permissionKey: 'sidebar.translations' },
            ],
          },
          {
            id: 'nav.admin.payment-methods',
            label: LIT('Payments Config'),
            path: '/admin/payment-methods',
            permissionKey: 'sidebar.payment-methods',
            children: [
              { id: 'nav.admin.payment-methods.landing', label: LIT('Payment Methods'), path: '/admin/payment-methods', permissionKey: 'sidebar.payment-methods' },
              { id: 'nav.admin.payment-gateways', label: LIT('Gateway Config'), path: '/admin/payment-gateways', permissionKey: 'sidebar.payment-gateways' },
            ],
          },
        ],
      },
      {
        id: 'nav.admin.bi',
        label: LIT('BI'),
        icon: '📊',
        path: '/admin/bi/dashboard',
        permissionKey: 'sidebar.bi',
        children: [
          { id: 'nav.admin.bi-dashboard', label: LIT('Dashboard'), path: '/admin/bi/dashboard', permissionKey: 'sidebar.bi-dashboard' },
          { id: 'nav.admin.bi-observability', label: LIT('Observability'), path: '/admin/bi/observability', permissionKey: 'sidebar.bi-observability' },
        ],
      },
    ],
  },
];

const { idToKey, keyToIds } = buildNavIdKeyMaps(ADMIN_NAV);

export const ADMIN_ID_TO_KEY: ReadonlyMap<string, string> = idToKey;
export const ADMIN_LEGACY_KEY_TO_ID: ReadonlyMap<string, string[]> = keyToIds;
