UPDATE permissions SET description = CASE permission_key
  WHEN 'dashboard.view' THEN 'View dashboard analytics and KPIs'
  WHEN 'dashboard.create' THEN 'Customize dashboard widgets'
  WHEN 'dashboard.edit' THEN 'Edit dashboard configuration'
  WHEN 'dashboard.delete' THEN 'Remove dashboard widgets'
  WHEN 'dashboard.approve' THEN 'Approve dashboard reports'
  WHEN 'dashboard.export' THEN 'Export dashboard data'
  WHEN 'bookings.view' THEN 'View booking list and details'
  WHEN 'bookings.create' THEN 'Create new bookings for resources'
  WHEN 'bookings.edit' THEN 'Edit existing booking details'
  WHEN 'bookings.delete' THEN 'Cancel or delete bookings'
  WHEN 'bookings.approve' THEN 'Approve pending booking requests'
  WHEN 'bookings.export' THEN 'Export booking reports'
  WHEN 'resources.view' THEN 'View resources and courts'
  WHEN 'resources.create' THEN 'Add new resources to a branch'
  WHEN 'resources.edit' THEN 'Edit resource details and pricing'
  WHEN 'resources.delete' THEN 'Remove or deactivate resources'
  WHEN 'resources.approve' THEN 'Approve resource availability requests'
  WHEN 'resources.export' THEN 'Export resource inventory'
  WHEN 'users.view' THEN 'View user accounts and profiles'
  WHEN 'users.create' THEN 'Create new user accounts'
  WHEN 'users.edit' THEN 'Edit user profile and details'
  WHEN 'users.delete' THEN 'Delete or suspend user accounts'
  WHEN 'users.approve' THEN 'Approve user registrations'
  WHEN 'users.export' THEN 'Export user data'
  WHEN 'roles.view' THEN 'View roles and their permissions'
  WHEN 'roles.create' THEN 'Create new roles'
  WHEN 'roles.edit' THEN 'Edit role name, slug, and description'
  WHEN 'roles.delete' THEN 'Delete custom roles'
  WHEN 'roles.approve' THEN 'Approve role assignments'
  WHEN 'roles.export' THEN 'Export role configurations'
  WHEN 'organisations.view' THEN 'View organisations and branches'
  WHEN 'organisations.create' THEN 'Create new organisations'
  WHEN 'organisations.edit' THEN 'Edit organisation details'
  WHEN 'organisations.delete' THEN 'Delete or deactivate organisations'
  WHEN 'organisations.approve' THEN 'Verify and approve organisations'
  WHEN 'organisations.export' THEN 'Export organisation data'
  WHEN 'marketplace.view' THEN 'View marketplace products and orders'
  WHEN 'marketplace.create' THEN 'Create marketplace listings'
  WHEN 'marketplace.edit' THEN 'Edit product details and pricing'
  WHEN 'marketplace.delete' THEN 'Remove marketplace listings'
  WHEN 'marketplace.approve' THEN 'Approve seller products'
  WHEN 'marketplace.export' THEN 'Export marketplace reports'
  WHEN 'payments.view' THEN 'View payment transactions'
  WHEN 'payments.create' THEN 'Initiate payment requests'
  WHEN 'payments.edit' THEN 'Edit payment records'
  WHEN 'payments.delete' THEN 'Void or reverse payments'
  WHEN 'payments.approve' THEN 'Approve payment disbursements'
  WHEN 'payments.export' THEN 'Export payment reports'
  WHEN 'coaching.view' THEN 'View coaching sessions and coaches'
  WHEN 'coaching.create' THEN 'Create coaching sessions'
  WHEN 'coaching.edit' THEN 'Edit coaching session details'
  WHEN 'coaching.delete' THEN 'Cancel coaching sessions'
  WHEN 'coaching.approve' THEN 'Approve coach applications'
  WHEN 'coaching.export' THEN 'Export coaching reports'
  WHEN 'academies.view' THEN 'View academies and programs'
  WHEN 'academies.create' THEN 'Create new academy programs'
  WHEN 'academies.edit' THEN 'Edit academy details'
  WHEN 'academies.delete' THEN 'Remove academy programs'
  WHEN 'academies.approve' THEN 'Approve academy enrollments'
  WHEN 'academies.export' THEN 'Export academy data'
  WHEN 'community.view' THEN 'View community events and posts'
  WHEN 'community.create' THEN 'Create community events'
  WHEN 'community.edit' THEN 'Edit community content'
  WHEN 'community.delete' THEN 'Remove community posts'
  WHEN 'community.approve' THEN 'Moderate community content'
  WHEN 'community.export' THEN 'Export community analytics'
  WHEN 'notifications.view' THEN 'View notification history'
  WHEN 'notifications.create' THEN 'Send push notifications'
  WHEN 'notifications.edit' THEN 'Edit notification templates'
  WHEN 'notifications.delete' THEN 'Clear notification history'
  WHEN 'notifications.approve' THEN 'Approve broadcast notifications'
  WHEN 'notifications.export' THEN 'Export notification logs'
  WHEN 'reports.view' THEN 'View system reports and analytics'
  WHEN 'reports.create' THEN 'Generate custom reports'
  WHEN 'reports.edit' THEN 'Edit report configurations'
  WHEN 'reports.delete' THEN 'Delete saved reports'
  WHEN 'reports.approve' THEN 'Approve financial reports'
  WHEN 'reports.export' THEN 'Export reports as CSV/PDF'
  WHEN 'settings.view' THEN 'View system settings'
  WHEN 'settings.create' THEN 'Add new settings'
  WHEN 'settings.edit' THEN 'Edit system configuration'
  WHEN 'settings.delete' THEN 'Reset settings to defaults'
  WHEN 'settings.approve' THEN 'Approve setting changes'
  WHEN 'settings.export' THEN 'Export settings backup'
  WHEN 'advertising.view' THEN 'View advertising campaigns'
  WHEN 'advertising.create' THEN 'Create ad campaigns'
  WHEN 'advertising.edit' THEN 'Edit campaign details'
  WHEN 'advertising.delete' THEN 'Remove ad campaigns'
  WHEN 'advertising.approve' THEN 'Approve ad submissions'
  WHEN 'advertising.export' THEN 'Export ad performance'
  WHEN 'cms.view' THEN 'View CMS pages and posts'
  WHEN 'cms.create' THEN 'Create new CMS pages'
  WHEN 'cms.edit' THEN 'Edit CMS content'
  WHEN 'cms.delete' THEN 'Delete CMS pages'
  WHEN 'cms.approve' THEN 'Publish draft content'
  WHEN 'cms.export' THEN 'Export CMS content'
  WHEN 'subscriptions.view' THEN 'View subscription plans'
  WHEN 'subscriptions.create' THEN 'Create subscription plans'
  WHEN 'subscriptions.edit' THEN 'Edit plan details and pricing'
  WHEN 'subscriptions.delete' THEN 'Archive subscription plans'
  WHEN 'subscriptions.approve' THEN 'Approve plan changes'
  WHEN 'subscriptions.export' THEN 'Export subscription data'
  ELSE description
END
WHERE description IS NULL;
