export const ErrorCodes = {
  // ── Auth ──
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_ACCOUNT_NOT_ACTIVE: 'AUTH_ACCOUNT_NOT_ACTIVE',
  AUTH_EMAIL_ALREADY_REGISTERED: 'AUTH_EMAIL_ALREADY_REGISTERED',
  AUTH_PHONE_ALREADY_REGISTERED: 'AUTH_PHONE_ALREADY_REGISTERED',
  AUTH_INVALID_RESET_TOKEN: 'AUTH_INVALID_RESET_TOKEN',
  AUTH_RESET_TOKEN_EXPIRED: 'AUTH_RESET_TOKEN_EXPIRED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',

  // ── User ──
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',

  // ── Booking ──
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  BOOKING_SLOT_UNAVAILABLE: 'BOOKING_SLOT_UNAVAILABLE',
  BOOKING_SLOT_MISALIGNED: 'BOOKING_SLOT_MISALIGNED',
  BOOKING_NO_SLOTS: 'BOOKING_NO_SLOTS',
  BOOKING_ALREADY_CANCELLED: 'BOOKING_ALREADY_CANCELLED',
  BOOKING_CANCELLATION_WINDOW_PASSED: 'BOOKING_CANCELLATION_WINDOW_PASSED',
  BOOKING_INVALID_TRANSITION: 'BOOKING_INVALID_TRANSITION',
  BOOKING_NOT_OWNER: 'BOOKING_NOT_OWNER',
  BOOKING_ALREADY_CONFIRMED: 'BOOKING_ALREADY_CONFIRMED',
  BOOKING_LOCK_FAILED: 'BOOKING_LOCK_FAILED',
  BOOKING_PREP_EXPIRED: 'BOOKING_PREP_EXPIRED',
  BOOKING_PREP_NOT_OWNER: 'BOOKING_PREP_NOT_OWNER',

  // ── Payment ──
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_INVALID_SIGNATURE: 'PAYMENT_INVALID_SIGNATURE',
  PAYMENT_GATEWAY_REJECTED: 'PAYMENT_GATEWAY_REJECTED',
  PAYMENT_TRANSACTION_NOT_FOUND: 'PAYMENT_TRANSACTION_NOT_FOUND',
  PAYMENT_GATEWAY_ERROR: 'PAYMENT_GATEWAY_ERROR',
  PAYMENT_LOCKED: 'PAYMENT_LOCKED',
  PAYMENT_ALREADY_PROCESSED: 'PAYMENT_ALREADY_PROCESSED',

  // ── Wallet ──
  WALLET_INSUFFICIENT_BALANCE: 'WALLET_INSUFFICIENT_BALANCE',
  WALLET_LOCKED: 'WALLET_LOCKED',
  WALLET_CONCURRENT_UPDATE: 'WALLET_CONCURRENT_UPDATE',
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',

  // ── Match ──
  MATCH_NOT_FOUND: 'MATCH_NOT_FOUND',
  MATCH_ALREADY_EXISTS: 'MATCH_ALREADY_EXISTS',
  MATCH_NOT_PUBLIC: 'MATCH_NOT_PUBLIC',

  // ── Organisation ──
  ORGANISATION_NOT_FOUND: 'ORGANISATION_NOT_FOUND',
  ORGANISATION_SUSPENDED: 'ORGANISATION_SUSPENDED',

  // ── Membership ──
  MEMBERSHIP_NOT_FOUND: 'MEMBERSHIP_NOT_FOUND',
  MEMBERSHIP_EXPIRED: 'MEMBERSHIP_EXPIRED',

  // ── Resource ──
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_UNAVAILABLE: 'RESOURCE_UNAVAILABLE',

  // ── RBAC ──
  RBAC_FORBIDDEN: 'RBAC_FORBIDDEN',
  RBAC_ROLE_NOT_FOUND: 'RBAC_ROLE_NOT_FOUND',
  RBAC_PERMISSION_DENIED: 'RBAC_PERMISSION_DENIED',

  // ── General Validation ──
  VALIDATION_REQUIRED: 'VALIDATION_REQUIRED',
  VALIDATION_INVALID_FORMAT: 'VALIDATION_INVALID_FORMAT',
  VALIDATION_INVALID_VALUE: 'VALIDATION_INVALID_VALUE',
  VALIDATION_MIN_LENGTH: 'VALIDATION_MIN_LENGTH',
  VALIDATION_MAX_LENGTH: 'VALIDATION_MAX_LENGTH',
  VALIDATION_PHONE_FORMAT: 'VALIDATION_PHONE_FORMAT',
  VALIDATION_INVALID_EMAIL: 'VALIDATION_INVALID_EMAIL',
  VALIDATION_INVALID_DATE: 'VALIDATION_INVALID_DATE',

  // ── System ──
  SYSTEM_INTERNAL_ERROR: 'SYSTEM_INTERNAL_ERROR',
  SYSTEM_SERVICE_UNAVAILABLE: 'SYSTEM_SERVICE_UNAVAILABLE',
  SYSTEM_DATABASE_ERROR: 'SYSTEM_DATABASE_ERROR',
  SYSTEM_RATE_LIMITED: 'SYSTEM_RATE_LIMITED',
  SYSTEM_TIMEOUT: 'SYSTEM_TIMEOUT',

  // ── Upload ──
  UPLOAD_INVALID_TYPE: 'UPLOAD_INVALID_TYPE',
  UPLOAD_TOO_LARGE: 'UPLOAD_TOO_LARGE',
  UPLOAD_FAILED: 'UPLOAD_FAILED',

  // ── Notification ──
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  NOTIFICATION_FAILED: 'NOTIFICATION_FAILED',

  // ── Academy ──
  ACADEMY_PROGRAM_NOT_FOUND: 'ACADEMY_PROGRAM_NOT_FOUND',
  ACADEMY_PROGRAM_CODE_EXISTS: 'ACADEMY_PROGRAM_CODE_EXISTS',
  ACADEMY_GROUP_NOT_FOUND: 'ACADEMY_GROUP_NOT_FOUND',
  ACADEMY_ENROLLMENT_NOT_FOUND: 'ACADEMY_ENROLLMENT_NOT_FOUND',
  ACADEMY_ENROLLMENT_EXISTS: 'ACADEMY_ENROLLMENT_EXISTS',
  ACADEMY_ATTENDANCE_NOT_FOUND: 'ACADEMY_ATTENDANCE_NOT_FOUND',
  ACADEMY_ATTENDANCE_EXISTS: 'ACADEMY_ATTENDANCE_EXISTS',
  ACADEMY_CAPACITY_EXCEEDED: 'ACADEMY_CAPACITY_EXCEEDED',
  ACADEMY_INVALID_TRANSITION: 'ACADEMY_INVALID_TRANSITION',
  ACADEMY_GROUP_FULL: 'ACADEMY_GROUP_FULL',
  ACADEMY_COACH_NOT_FOUND: 'ACADEMY_COACH_NOT_FOUND',
  ACADEMY_PLAYER_ALREADY_ASSIGNED: 'ACADEMY_PLAYER_ALREADY_ASSIGNED',
  ACADEMY_INVALID_SESSION: 'ACADEMY_INVALID_SESSION',
  ACADEMY_WAITING_LIST_FULL: 'ACADEMY_WAITING_LIST_FULL',

  // ── Tournament ──
  TOURNAMENT_NOT_FOUND: 'TOURNAMENT_NOT_FOUND',
  TOURNAMENT_CODE_EXISTS: 'TOURNAMENT_CODE_EXISTS',
  TOURNAMENT_REGISTRATION_NOT_FOUND: 'TOURNAMENT_REGISTRATION_NOT_FOUND',
  TOURNAMENT_REGISTRATION_EXISTS: 'TOURNAMENT_REGISTRATION_EXISTS',
  TOURNAMENT_MATCH_NOT_FOUND: 'TOURNAMENT_MATCH_NOT_FOUND',
  TOURNAMENT_GROUP_NOT_FOUND: 'TOURNAMENT_GROUP_NOT_FOUND',
  TOURNAMENT_CAPACITY_EXCEEDED: 'TOURNAMENT_CAPACITY_EXCEEDED',
  TOURNAMENT_INVALID_TRANSITION: 'TOURNAMENT_INVALID_TRANSITION',
  TOURNAMENT_REGISTRATION_CLOSED: 'TOURNAMENT_REGISTRATION_CLOSED',
  TOURNAMENT_CAPACITY_FULL: 'TOURNAMENT_CAPACITY_FULL',
  TOURNAMENT_INVALID_FORMAT: 'TOURNAMENT_INVALID_FORMAT',
  TOURNAMENT_INVALID_SCORE: 'TOURNAMENT_INVALID_SCORE',

  // ── League / Season ──
  SEASON_NOT_FOUND: 'SEASON_NOT_FOUND',
  SEASON_INVALID_TRANSITION: 'SEASON_INVALID_TRANSITION',
  LEAGUE_NOT_FOUND: 'LEAGUE_NOT_FOUND',
  LEAGUE_CODE_EXISTS: 'LEAGUE_CODE_EXISTS',
  LEAGUE_INVALID_TRANSITION: 'LEAGUE_INVALID_TRANSITION',
  LEAGUE_FULL: 'LEAGUE_FULL',
  LEAGUE_REGISTRATION_CLOSED: 'LEAGUE_REGISTRATION_CLOSED',
  DIVISION_NOT_FOUND: 'DIVISION_NOT_FOUND',
  DIVISION_FULL: 'DIVISION_FULL',
  DIVISION_TEAM_EXISTS: 'DIVISION_TEAM_EXISTS',
  LEAGUE_TEAM_NOT_FOUND: 'LEAGUE_TEAM_NOT_FOUND',
  LEAGUE_TEAM_EXISTS: 'LEAGUE_TEAM_EXISTS',
  LEAGUE_MATCH_NOT_FOUND: 'LEAGUE_MATCH_NOT_FOUND',
  LEAGUE_INVALID_SCORE: 'LEAGUE_INVALID_SCORE',
  LEAGUE_RESULT_EXISTS: 'LEAGUE_RESULT_EXISTS',
  LEAGUE_STANDING_NOT_FOUND: 'LEAGUE_STANDING_NOT_FOUND',

  // ── Player Experience ──
  PLAYER_DEVICE_NOT_FOUND: 'PLAYER_DEVICE_NOT_FOUND',
  PLAYER_FAVORITE_EXISTS: 'PLAYER_FAVORITE_EXISTS',
  PLAYER_ACHIEVEMENT_NOT_FOUND: 'PLAYER_ACHIEVEMENT_NOT_FOUND',

  // ── Coach / Referee ──
  REFEREE_NOT_FOUND: 'REFEREE_NOT_FOUND',
  REFEREE_ALREADY_ASSIGNED: 'REFEREE_ALREADY_ASSIGNED',
  COACH_NOT_FOUND: 'COACH_NOT_FOUND',
  COACH_UNAVAILABLE: 'COACH_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export const SuccessCodes = {
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
  AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
  BOOKING_CREATED: 'BOOKING_CREATED',
  BOOKING_CONFIRMED: 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  BOOKING_COMPLETED: 'BOOKING_COMPLETED',
  BOOKING_PREPARED: 'BOOKING_PREPARED',
  PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
  PAYMENT_REFUNDED: 'PAYMENT_REFUNDED',
  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  WALLET_DEPOSITED: 'WALLET_DEPOSITED',
  WALLET_WITHDRAWN: 'WALLET_WITHDRAWN',
  USER_UPDATED: 'USER_UPDATED',
  USER_CREATED: 'USER_CREATED',
  USER_DELETED: 'USER_DELETED',
  MATCH_CREATED: 'MATCH_CREATED',
  ORGANISATION_CREATED: 'ORGANISATION_CREATED',
  ORGANISATION_UPDATED: 'ORGANISATION_UPDATED',
  NOTIFICATION_SENT: 'NOTIFICATION_SENT',
  NOTIFICATION_READ: 'NOTIFICATION_READ',
} as const;

export type SuccessCode = (typeof SuccessCodes)[keyof typeof SuccessCodes];

export function errorCodeToTranslationKey(code: string): string {
  const key = code.toLowerCase().replace(/_/g, '.');
  return `error.${key}`;
}

export function successCodeToTranslationKey(code: string): string {
  const key = code.toLowerCase().replace(/_/g, '.');
  return `success.${key}`;
}
