export type AuditAction =
  | 'USER.LOGIN'
  | 'USER.LOGOUT'
  | 'USER.REGISTER'
  | 'USER.LOGIN_FAILED'
  | 'USER.PASSWORD_RESET'
  | 'USER.PASSWORD_CHANGE'
  | 'USER.DELETE'
  | 'ROLE.CREATE'
  | 'ROLE.UPDATE'
  | 'ROLE.DELETE'
  | 'PERMISSION.ASSIGN'
  | 'PERMISSION.REVOKE'
  | 'PERMISSION.SYNC'
  | 'ORGANISATION.CREATE'
  | 'ORGANISATION.UPDATE'
  | 'ORGANISATION.DELETE'
  | 'ORGANISATION.VERIFY'
  | 'WALLET.CREATE'
  | 'WALLET.CREDIT'
  | 'WALLET.DEBIT'
  | 'WALLET.ADJUST'
  | 'SETTLEMENT.CREATE'
  | 'SETTLEMENT.PROCESS'
  | 'SETTLEMENT.APPROVE'
  | 'SETTLEMENT.REJECT'
  | 'BOOKING.CREATE'
  | 'BOOKING.CANCEL'
  | 'BOOKING.REFUND'
  | 'BOOKING.STATUS_CHANGE'
  | 'MARKETPLACE.PRODUCT_CREATE'
  | 'MARKETPLACE.PRODUCT_UPDATE'
  | 'MARKETPLACE.PRODUCT_DELETE'
  | 'MARKETPLACE.ORDER_STATUS'
  | 'FINANCIAL.TRANSACTION'
  | 'UPLOAD.CREATE'
  | 'UPLOAD.DELETE'
  | 'SETTINGS.UPDATE'
  | 'FEATURE_FLAG.TOGGLE'
  | 'CMS.UPDATE'
  | 'ADMIN.ACTION'
  | 'SUBSCRIPTION.CREATED'
  | 'SUBSCRIPTION.APPROVED'
  | 'SUBSCRIPTION.REJECTED'
  | 'SUBSCRIPTION.ACTIVATED'
  | 'SUBSCRIPTION.RENEWED'
  | 'SUBSCRIPTION.EXPIRED'
  | 'SUBSCRIPTION.CANCELLED'
  | 'SUBSCRIPTION.SUSPENDED'
  | 'SUBSCRIPTION.RESUMED'
  | 'SUBSCRIPTION.EXTENDED'
  | 'SUBSCRIPTION.UPDATED';

export interface AuditEntry {
  userId: number;
  action: AuditAction;
  resource: string;
  resourceId?: number | string;
  details?: Record<string, unknown>;
  ip?: string;
  userAgent?: string;
}
