-- ============================================================================
-- Migration 065: Extended component style tokens
-- ============================================================================

USE courtzon_v2;

INSERT IGNORE INTO design_tokens (token_key, token_type, default_value, category, description) VALUES
  ('checkbox-size', 'size', '16px', 'component-checkbox', 'Checkbox control size'),
  ('checkbox-border-radius', 'radius', '4px', 'component-checkbox', 'Checkbox corner radius'),
  ('checkbox-accent-color', 'color', 'var(--color-primary)', 'component-checkbox', 'Checkbox checked color'),
  ('radio-size', 'size', '16px', 'component-radio', 'Radio control size'),
  ('radio-accent-color', 'color', 'var(--color-primary)', 'component-radio', 'Radio selected color'),
  ('switch-width', 'size', '44px', 'component-switch', 'Toggle switch width'),
  ('switch-height', 'size', '24px', 'component-switch', 'Toggle switch height'),
  ('switch-thumb-size', 'size', '20px', 'component-switch', 'Toggle thumb size'),
  ('switch-on-color', 'color', 'var(--color-primary)', 'component-switch', 'Toggle on track color'),
  ('switch-off-color', 'color', 'var(--color-border)', 'component-switch', 'Toggle off track color'),
  ('link-font-size', 'size', '14px', 'component-link', 'Link font size'),
  ('link-color', 'color', 'var(--color-primary)', 'component-link', 'Link color'),
  ('link-hover-color', 'color', 'var(--color-primary-dark)', 'component-link', 'Link hover color'),
  ('link-font-weight', 'other', '500', 'component-link', 'Link font weight'),
  ('heading-h1-size', 'size', '30px', 'component-heading', 'H1 font size'),
  ('heading-h2-size', 'size', '24px', 'component-heading', 'H2 font size'),
  ('heading-h3-size', 'size', '20px', 'component-heading', 'H3 font size'),
  ('heading-font-family', 'font', 'var(--font-heading)', 'component-heading', 'Heading font family'),
  ('heading-color', 'color', 'var(--color-text)', 'component-heading', 'Heading text color'),
  ('heading-font-weight', 'other', '700', 'component-heading', 'Heading font weight'),
  ('sidebar-width', 'size', '260px', 'component-sidebar', 'Sidebar width'),
  ('sidebar-bg', 'color', 'var(--color-surface)', 'component-sidebar', 'Sidebar background'),
  ('sidebar-item-padding-x', 'size', '12px', 'component-sidebar', 'Sidebar item padding X'),
  ('sidebar-item-padding-y', 'size', '10px', 'component-sidebar', 'Sidebar item padding Y'),
  ('sidebar-item-radius', 'radius', 'var(--radius-md)', 'component-sidebar', 'Sidebar item radius'),
  ('sidebar-active-bg', 'color', 'var(--color-primary-bg)', 'component-sidebar', 'Active item background'),
  ('sidebar-active-color', 'color', 'var(--color-primary)', 'component-sidebar', 'Active item text'),
  ('toast-padding', 'size', '16px', 'component-toast', 'Toast padding'),
  ('toast-radius', 'radius', 'var(--radius-md)', 'component-toast', 'Toast corner radius'),
  ('toast-font-size', 'size', '14px', 'component-toast', 'Toast font size'),
  ('toast-shadow', 'shadow', 'var(--shadow-lg)', 'component-toast', 'Toast shadow'),
  ('tabs-font-size', 'size', '14px', 'component-tabs', 'Tab font size'),
  ('tabs-padding-x', 'size', '16px', 'component-tabs', 'Tab padding X'),
  ('tabs-padding-y', 'size', '10px', 'component-tabs', 'Tab padding Y'),
  ('tabs-active-color', 'color', 'var(--color-primary)', 'component-tabs', 'Active tab color'),
  ('tabs-border-color', 'color', 'var(--color-border)', 'component-tabs', 'Tab border color'),
  ('pagination-font-size', 'size', '14px', 'component-pagination', 'Pagination font size'),
  ('pagination-item-size', 'size', '36px', 'component-pagination', 'Pagination button size'),
  ('pagination-active-bg', 'color', 'var(--color-primary)', 'component-pagination', 'Active page background'),
  ('pagination-active-color', 'color', '#FFFFFF', 'component-pagination', 'Active page text'),
  ('spinner-size', 'size', '32px', 'component-spinner', 'Spinner size'),
  ('spinner-color', 'color', 'var(--color-primary)', 'component-spinner', 'Spinner color'),
  ('file-button-radius', 'radius', '9999px', 'component-file', 'File input button radius'),
  ('file-button-padding-x', 'size', '16px', 'component-file', 'File button padding X'),
  ('file-button-padding-y', 'size', '8px', 'component-file', 'File button padding Y'),
  ('navbar-height', 'size', '56px', 'component-navbar', 'Top navbar height'),
  ('navbar-bg', 'color', 'var(--color-surface)', 'component-navbar', 'Navbar background'),
  ('navbar-border-color', 'color', 'var(--color-border)', 'component-navbar', 'Navbar border');
